### ISSUE TITLE
ConnectAsync not reconnecting after sending QuitMessage

### ISSUE THREAD

**Issue by kimimaru4000** [Fredi/NetIRC#10]
If I send a quit message with `IrcClient.SendAsync(new QuitMessage(string.Empty));` and then attempt to connect with `await IrcClient.ConnectAsync();`, the reconnect never completes and hangs. This doesn't happen the first time around.

Here's an example:
```
private async Task AwaitConnected()
{
    if (Connecting == true)
    {
        Logger.Information("Already waiting to connect"); //I see this message each reconnect after the first, after sending the QUIT message
        return;
    }

    Connecting = true;
    
    await IrcClient.ConnectAsync();
    
    Connecting = false;

    Logger.Verbose("Finished connecting to IRC server!"); //This log is fired the first time upon connecting, but never on the second after sending the QUIT message
}
```

I'm running this with .NET 5 on Linux Mint 20.3 Una. [Here's the relevant part of my code](https://codeberg.org/kimimaru/TRBot/src/commit/723487eec18ea3776c6a854ecfa643951103fe32/TRBot/TRBot.Connection/ClientServices/IRC/IRCClientService.cs#L118).

**Comment by fredimachado** [comment]
You could try handling the `Disconnected` event in `TcpClientConnection` and use it to make sure the connection was closed.
It's worth pointing that in your `OnIRCMessageParsed` event handler there's a check for the quit message, but the client can receive quit messages when other people quit as well, so in that case the best would be checking the nick as well.

**Comment by kimimaru4000** [comment]
Unfortunately, that didn't fix the issue. After handling the `Disconnected` event and trying to reconnect, it still hangs and never connects. Is it necessary to dispose the client and TCP connection and create new ones in this case?

**Comment by fredimachado** [comment]
I was testing disconnecting and connecting again multiple times using my very crude desktop client (https://github.com/fredimachado/NetIRC.Desktop) and it seems to be working fine. I noticed I'm always creating a new instance of the Client class though, so I think the answer to your last question might be yes.

**Comment by fredimachado** [comment]
I've tried quitting and reconnecting without creating a new Client instance, and it didn't work. So I've updated the library to dispose and create a new instance of the TcpClient when ConnectAsync is called. Could you please try with version 1.1.1 and let me know if it works for you? Cheers!

**Comment by kimimaru4000** [comment]
Thanks so much for getting on this! I tried out 1.1.1 and it works perfectly. I greatly appreciate the help!

**Comment by fredimachado** [comment]
> Thanks so much for getting on this! I tried out 1.1.1 and it works perfectly. I greatly appreciate the help!

Awesome! Thanks for taking the time to open the issue. Cheers!
