### ISSUE TITLE
Documentation / Examples

### ISSUE THREAD

**Issue by KoalaBear84** [Fredi/NetIRC#4]
I've tried to use it, but it looks like you need to connect twice, and it says it is trying to connect to an already connected host.

IRC is hard, this is what I tried:

```csharp
const string host = "irc.thehost.net";

Console.WriteLine("Connecting...");
NetIRC.Connection.TcpClientConnection tcpClientConnection = new NetIRC.Connection.TcpClientConnection();
await tcpClientConnection.ConnectAsync(host, 6667);

Console.WriteLine("Create user...");
User ircUser = new User("Username", "Real name");

Console.WriteLine("Create client...");
Client ircClient = new Client(ircUser, tcpClientConnection);

Console.WriteLine("Connecting...");
await ircClient.ConnectAsync(host);
Console.WriteLine("Connected.");
```

Sorry, I can't use it because it is not clear to me. Somewhere I need to join a channel also, so I can send a message to it.

Any documentation, examples or test client would be nice. Thanks in advance!

**Comment by fredimachado** [comment]
Hey,

Sorry, I've only seen your issue now :(

The client will manage the connection for you, so in your attempt to use it you tried to connect before creating the client instance.

You should do something like this:

```csharp
Console.WriteLine("Create user...");
var ircUser = new User("Username", "Real name");

Console.WriteLine("Create client...");
var client = new Client(ircUser, new TcpClientConnection())

Console.WriteLine("Connecting...");
await ircClient.ConnectAsync(host);
Console.WriteLine("Connected.");
```

You could have a look at the Console client example in here: https://github.com/fredimachado/NetIRC/blob/master/src/NetIRC.ConsoleCli/Program.cs

I'll do some more work on this project soon, and I plan to add more examples and documentation.

Thanks and sorry for the late response.

Fredi

**Comment by KoalaBear84** [comment]
Thanks Fredi.

Could you add this simple example to the main page of the repo? And/or include the info that there is a example console application?

Thanks!

**Comment by halomakes** [comment]
Did you figure out how to join a channel? I'm using `await client.SendAsync(new JoinMessage("#carrots"));` and it joins but then my app immediately crashes.

System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
InnerException IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by fredimachado** [comment]
Hey @KoalaBear84,
I've added information about the sample console app in the main README.
Also, the sample was updated and it's heavily commented now. :)

**Comment by KoalaBear84** [comment]
Great 👍
