### ISSUE TITLE
Message splitting

### ISSUE THREAD

**Issue by LaineZ** [Fredi/NetIRC#6]
If message encoded in UTF-8 and more than ~512 bytes it breaks the message

**Comment by halomakes** [comment]
Can you add some more clarification on what you meant by "breaks the message".  From my use of this library with Unicode messages get truncated if they are too long.  I'm not sure if I would want the client to automatically split content into multiple messages for anything other than a PrivMsg

**Comment by LaineZ** [comment]
The failure of message looks like this (Message get truncated, last symbols replaces in Replacement Character (U+FFFD: �)):
![Error](https://i.imgur.com/LDDz2Kb.png)

**Comment by fredimachado** [comment]
Hi @LaineZ,
Do you know how to reproduce this? It would be nice if you had a sample raw message to share so I can add it to the test project and see what happens.

**Comment by LaineZ** [comment]
@fredimachado 
Basic example to reproduce (using 1.1.0-alpha version from nuget):
```cs
using NetIRC;
using NetIRC.Connection;
using NetIRC.Messages;
using System;
using System.Threading.Tasks;

namespace IRCReproduce
{
    public class Program
    {
        private const string nickName = "NetIRCConsoleClient";
        private const string channel = "#fl-studio";
        private static Client client;

        static void Main(string[] args)
        {
            var user = new User(nickName, "NetIRC");
            var tcpConnection = new TcpClientConnection("irc.esper.net", 6667);

            using (client = new Client(user, tcpConnection))
            {
                client.RawDataReceived += Client_RawDataReceived;
                client.RegistrationCompleted += EventHub_RegistrationCompleted;
                client.RegisterCustomMessageHandlers(typeof(Program).Assembly);
                Task.Run(() => client.ConnectAsync());
                Console.Read();
            }
        }

        private static void Client_RawDataReceived(Client client, string rawData)
        {
            WriteLine(rawData);
        }

        private static async void EventHub_RegistrationCompleted(object sender, EventArgs e)
        {
            await client.SendAsync(new JoinMessage(channel));
            // Here a message that gets truncated
            await client.SendAsync(new PrivMsgMessage(channel, "Я даю вам шанс сдаться и отдать если хотите жизинь, пока не поздно уведите свое нек-чемное сопротивление, решайте! " +
                "И каков ваш ответ? Нет? Ну ладно вы сами подписали себе смертный приговор. Уничтожте всех до единого повстанца! " +
                "Не дайте им уничтожить последний аванпост снабжения. Используйте все силы чтобы его защитить он нам нужен!... Связь прервана."));
        }

        // Just a simple Console.WriteLine wrapper to allow us to change font color
        public static void WriteLine(string value, ConsoleColor color = ConsoleColor.White)
        {
            var previousColor = Console.ForegroundColor;
            Console.ForegroundColor = color;
            Console.WriteLine(value);
            Console.ForegroundColor = previousColor;
        }
    }
}
```

**Comment by LaineZ** [comment]
Currently, I have temporary solution:
https://github.com/LaineZ/fs24bot3/blob/master/fs24bot3/Bot.cs#L157-L182

**Comment by fredimachado** [comment]
Thanks for the extra information @LaineZ. It's more clear to me now.
I've implemented simple PrivMsg splitting for now.
Could you please try version 1.1.2-preview.1 and let me know if it works for you?

**Comment by LaineZ** [comment]
Thanks for reply @fredimachado. I tried 1.1.2-preview.1 version. But splitting seems to be works only on ASCII or other 1 byte per char encoding (like windows-1251). But if you try to send a message fully contained UTF-8 characters, like this:

```            
await client.SendAsync(new PrivMsgMessage(channel, "Я даю вам шанс сдаться и отдать если хотите жизинь, пока не поздно уведите свое нек-чемное сопротивление, решайте! " +
                "И каков ваш ответ? Нет? Ну ладно вы сами подписали себе смертный приговор. Уничтожте всех до единого повстанца! " +
                "Не дайте им уничтожить последний аванпост снабжения. Используйте все силы чтобы его защитить он нам нужен!... Связь прервана."));
```

You get same result described above:

> The failure of message looks like this (Message get truncated, last symbols replaces in Replacement Character (U+FFFD: �)): ![Error](https://camo.githubusercontent.com/d75911f84eefd43c1bc9e71170a24687085dd34d0a84ef7e946d8f5a2745fa20/68747470733a2f2f692e696d6775722e636f6d2f4c44447a324b622e706e67)

Because UTF-8 characters have a variable length and basic splitting algorithms 1-byte-per-char works incorrectly. 

https://stackoverflow.com/questions/45201142/find-nearest-safe-split-in-byte-array-containing-utf-8-data

### You can also check fs24_bot code

https://github.com/LaineZ/fs24bot3/blob/master/fs24bot3/Helpers/MessageHelper.cs#L78-L123 and https://github.com/LaineZ/fs24bot3/blob/master/fs24bot3/Bot.cs#L157-L182

**Comment by fredimachado** [comment]
Hey @LaineZ, thanks for sending even more information. I think version `1.1.2-preview.2` might fix your issue.
I did some tests in mIRC and noticed it splits your sample message every ~390 bytes (not characters).
So it looked like this:
> \<Fredi> Я даю вам шанс сдаться и отдать если хотите жизинь, пока не поздно уведите свое нек-чемное сопротивление, решайте! И каков ваш ответ? Нет? Ну ладно вы сами подписали себе смертный приговор. Уничтожте всех до единого 
> \<Fredi> повстанца! Не дайте им уничтожить последний аванпост снабжения. Используйте все силы чтобы его защитить он нам нужен!... Связь прервана.

As far as I know the client can send a maximum of 512 bytes per message (including the carriage-return and line-feed at the end) so I'm splitting every ~400 bytes to leave space for the command and target. Would that be ok?

Please let me know if `1.1.2-preview.2` works for you.

**Comment by LaineZ** [comment]
Hello @fredimachado, thanks for update! Now ```1.1.2-preview.2``` works for me!

![ev32GoJ3NI](https://user-images.githubusercontent.com/19235522/153709105-8ac65099-188b-41c3-b3a3-9e1ace0d3ba6.png)

**Comment by fredimachado** [comment]
Awesome! Thanks for taking the time to help moving this forward and testing this :)
I'll make the implementation cleaner and release version 1.1.2 soon.
